name: Remove word from dictionary
description: Let us know about words that you think should be removed from the game's dictionary
title: "[Remove words]: "
body:
  - type: markdown
    attributes:
      value: |
        Note: The repository owner will make the final decision about whether to remove words to the dictionary.
  - type: textarea
    id: request
    attributes:
      label: What words do you want to remove? (The repository owner will make the final decision about whether to remove words from the dictionary.)
    validations:
      required: true
