import type {PrimaryColor} from "../Types";

// All possible colors, sorted into a visually appealing order when displayed in an 8x11 grid
export const palette: PrimaryColor[][] = [
  ["yellow", "yellow", "red", "red", "red", "red", "red"],
  ["yellow", "red", "red"],
  ["yellow", "yellow", "red", "red", "red"],
  ["yellow", "yellow", "yellow", "red", "red", "red", "red"],
  ["yellow", "yellow", "red", "red"],
  ["yellow", "yellow", "yellow", "yellow", "red", "red", "red"],
  ["yellow", "yellow", "yellow", "red", "red"],
  ["yellow", "yellow", "red"],
  ["yellow", "yellow", "yellow", "blue", "red", "red", "red"],
  ["yellow", "yellow", "yellow", "blue", "red", "red"],
  ["yellow", "yellow", "yellow", "yellow", "blue", "red", "red"],
  ["yellow", "yellow", "yellow", "yellow", "yellow", "red", "red"],
  ["yellow", "yellow", "yellow", "red"],
  ["yellow", "yellow", "yellow", "yellow", "red"],
  ["yellow", "yellow", "yellow", "yellow", "yellow", "red"],
  ["yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "red"],
  ["yellow", "yellow", "blue", "red", "red"],
  ["yellow", "yellow", "yellow", "blue", "red"],
  ["yellow", "yellow", "yellow", "yellow", "blue", "red"],
  ["yellow", "yellow", "yellow", "yellow", "yellow", "blue", "red"],
  ["yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "blue"],
  ["yellow", "yellow", "yellow", "yellow", "yellow", "blue"],
  ["yellow", "yellow", "yellow", "yellow", "blue"],
  ["yellow", "yellow", "yellow"],
  ["yellow", "yellow", "yellow", "blue", "blue", "red", "red"],
  ["yellow", "yellow", "blue", "red"],
  ["yellow", "yellow", "yellow", "blue", "blue", "red"],
  ["yellow", "yellow", "yellow", "yellow", "blue", "blue", "red"],
  ["yellow", "yellow", "yellow", "yellow", "yellow", "blue", "blue"],
  ["yellow", "yellow", "blue"],
  ["yellow", "yellow", "yellow", "blue"],
  ["yellow", "yellow", "blue", "blue", "blue"],
  ["yellow", "yellow", "blue", "blue", "red"],
  ["yellow", "yellow", "yellow", "blue", "blue", "blue", "red"],
  ["yellow", "yellow", "yellow", "blue", "blue", "blue", "blue"],
  ["yellow", "yellow", "blue", "blue"],
  ["yellow", "yellow", "yellow", "blue", "blue"],
  ["yellow", "yellow", "yellow", "yellow", "blue", "blue", "blue"],
  ["yellow", "blue", "blue"],
  ["yellow", "yellow", "blue", "blue", "blue", "blue", "blue"],
  ["yellow", "blue", "red"],
  ["yellow", "blue", "blue", "red"],
  ["yellow", "yellow", "blue", "blue", "blue", "red"],
  ["yellow", "yellow", "blue", "blue", "blue", "blue", "red"],
  ["yellow", "blue", "blue", "blue", "blue"],
  ["yellow", "blue", "blue", "blue", "blue", "blue"],
  ["yellow", "blue", "blue", "blue", "blue", "blue", "blue"],
  ["yellow", "blue", "blue", "blue"],
  ["yellow", "yellow", "blue", "blue", "blue", "red", "red"],
  ["blue", "blue", "blue", "blue", "blue", "red"],
  ["blue", "blue", "blue", "blue", "red"],
  ["yellow", "blue", "blue", "blue", "red"],
  ["yellow", "blue", "blue", "blue", "blue", "red"],
  ["yellow", "blue", "blue", "blue", "blue", "blue", "red"],
  ["blue", "blue", "blue"],
  ["blue", "blue", "blue", "blue", "blue", "blue", "red"],
  ["yellow", "blue", "blue", "red", "red"],
  ["yellow", "blue", "blue", "blue", "red", "red"],
  ["yellow", "blue", "blue", "blue", "blue", "red", "red"],
  ["blue", "blue", "blue", "red"],
  ["blue", "blue", "blue", "blue", "blue", "red", "red"],
  ["blue", "blue", "red"],
  ["blue", "blue", "blue", "blue", "red", "red", "red"],
  ["blue", "blue", "blue", "red", "red"],
  ["yellow", "blue", "blue", "blue", "red", "red", "red"],
  ["yellow", "blue", "blue", "red", "red", "red"],
  ["yellow", "blue", "blue", "red", "red", "red", "red"],
  ["blue", "blue", "red", "red"],
  ["blue", "blue", "blue", "red", "red", "red", "red"],
  ["blue", "blue", "red", "red", "red"],
  ["blue", "red", "red"],
  ["blue", "blue", "red", "red", "red", "red", "red"],
  ["yellow", "blue", "red", "red"],
  ["yellow", "blue", "red", "red", "red"],
  ["yellow", "blue", "red", "red", "red", "red"],
  ["yellow", "blue", "red", "red", "red", "red", "red"],
  ["blue", "red", "red", "red"],
  ["blue", "red", "red", "red", "red"],
  ["blue", "red", "red", "red", "red", "red"],
  ["blue", "red", "red", "red", "red", "red", "red"],
  ["yellow", "yellow", "blue", "blue", "red", "red", "red"],
  ["yellow", "yellow", "blue", "red", "red", "red"],
  ["yellow", "yellow", "blue", "red", "red", "red", "red"],
  ["yellow", "red", "red", "red"],
  ["yellow", "red", "red", "red", "red"],
  ["yellow", "red", "red", "red", "red", "red"],
  ["yellow", "red", "red", "red", "red", "red", "red"],
  ["red", "red", "red"],
];
